<?php
/**
 * Inlines the editor-only `window.kntntGpxBlocks` registry payload.
 *
 * Exposes the validated tile-provider and overlay registries to the block
 * editor so the GPX Map block's Inspector controls can enumerate them. Both
 * the per-block tile-provider dropdown (issue #79) and the overlay toggles
 * (issue #80) read from the same global; this enqueuer is the single source
 * the editor JS consults.
 *
 * The payload is JSON-encoded and attached as a `'before'` inline script on
 * the GPX Map block's editor handle, so it lands in the editor document
 * before the block's React entry runs and reads the global. API keys are
 * deliberately excluded from the payload: attribute-path keys are per-block
 * (`attributes.tileApiKeys` and `attributes.tileOverlayApiKeys`, both
 * provider-keyed objects) and never leave PHP except as the substituted
 * `{KEY}` value in the rendered tile URL, and PHP-supplied keys (engaged
 * via the optional `apiKey` field on a `kntnt_gpx_blocks_tile_providers`
 * or `kntnt_gpx_blocks_tile_overlays` callback) are substituted
 * server-side before the URL reaches the editor — the editor receives a
 * boolean `apiKeyManagedExternally` flag per provider but never the key
 * itself.
 *
 * @package Kntnt\Gpx_Blocks
 * @since   1.0.0
 */

declare( strict_types = 1 );

namespace Kntnt\Gpx_Blocks\Bootstrap;

use Kntnt\Gpx_Blocks\Plugin;
use Kntnt\Gpx_Blocks\Rendering\Tile_Layer_Registry;

/**
 * Enqueues the editor-only `window.kntntGpxBlocks` registry payload.
 *
 * Constructed once by Plugin and bound to `enqueue_block_editor_assets` so
 * the global is set up on every editor request — post, site, widgets, and
 * navigation — before the GPX Map block's editor script reads from it.
 *
 * @package Kntnt\Gpx_Blocks
 * @since 1.0.0
 */
final class Editor_Data_Enqueuer {

	/**
	 * Editor script handle generated by `register_block_type()` for the GPX
	 * Map block.
	 *
	 * Follows WordPress's `generate_block_asset_handle()` convention:
	 * `<namespace>-<slug>-editor-script`. The block.json `name` is
	 * `kntnt-gpx-blocks/map`, so the handle is
	 * `kntnt-gpx-blocks-map-editor-script`.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	private const MAP_EDITOR_HANDLE = 'kntnt-gpx-blocks-map-editor-script';

	/**
	 * Constructs the enqueuer with an injectable registry.
	 *
	 * Tests inject a synthetic registry; production wiring uses a fresh
	 * `Tile_Layer_Registry` per request (its filter-evaluation cache is
	 * per-instance and that is fine for a single editor render).
	 *
	 * @since 1.0.0
	 *
	 * @param Tile_Layer_Registry|null $registry Tile-layer registry, or null
	 *                                           to construct a default one
	 *                                           lazily inside `enqueue()`.
	 */
	public function __construct( private readonly ?Tile_Layer_Registry $registry = null ) {}

	/**
	 * Builds the editor data payload and inlines it as a `before` script.
	 *
	 * Wired to `enqueue_block_editor_assets`. Reads the validated provider
	 * and overlay registries and forwards the fields the editor's Inspector
	 * controls and `MapEditorPreview` need: `label` and `requiresKey` drive
	 * the dropdown and the conditional API-key text field, the optional
	 * `signupUrl` powers the "Get one" help-text link, and the URL /
	 * attribution / maxZoom / optional subdomains let the preview mount the
	 * selected provider's tile layer directly via `L.tileLayer()`. API keys
	 * are deliberately *not* in the payload — they remain a per-block
	 * attribute (`tileApiKeys[ tileProvider ]`) and reach the browser only
	 * as the substituted `{KEY}` value at render time. When JSON encoding
	 * fails or the
	 * inline-script call is unavailable, a warning is logged and the method
	 * returns silently — the editor reads `window.kntntGpxBlocks` defensively
	 * and degrades to an empty Tiles dropdown rather than throwing.
	 *
	 * @since 1.0.0
	 */
	public function enqueue(): void {

		// Resolve the registry from the constructor or build a default.
		$registry = $this->registry ?? new Tile_Layer_Registry();

		// Compose the payload from the validated registries. Both lists are
		// keyed by id; the editor reads `id` and `label` per entry.
		$payload = [
			'providers' => self::shape_providers( $registry->get_providers() ),
			'overlays'  => self::shape_overlays( $registry->get_overlays() ),
		];

		// Encode the payload. wp_json_encode() returns false on failure, in
		// which case we log a warning and bail rather than emit an invalid
		// global.
		$json = wp_json_encode( $payload );
		if ( ! is_string( $json ) ) {
			Plugin::warning( 'Editor_Data_Enqueuer: wp_json_encode failed; window.kntntGpxBlocks not emitted.' );
			return;
		}

		// Attach the inline script to the GPX Map block's editor handle so
		// the global is set up before the React entry reads it. Position
		// `before` ensures the assignment runs before the entry's IIFE.
		$inline = sprintf( 'window.kntntGpxBlocks = %s;', $json );
		wp_add_inline_script( self::MAP_EDITOR_HANDLE, $inline, 'before' );

	}

	/**
	 * Shapes the provider registry for the editor payload.
	 *
	 * Forwards the nested provider/style hierarchy verbatim into the
	 * inline payload so the editor's `TilesPanel` can drive its two
	 * `SelectControl`s plus the conditional API-key field, and so
	 * `MapEditorPreview` can mount the resolved style's tile layer via
	 * `L.tileLayer()`. Provider-level fields surfaced: `label`,
	 * `requiresKey`, `default`, optional `signupUrl`, optional
	 * `subdomains`, and `apiKeyManagedExternally` (the boolean flag the
	 * editor reads to decide whether to render the per-provider API-key
	 * TextControl). Per-style fields surfaced under `styles[ id ]`:
	 * `label`, `url` (with `{KEY}` left intact for the attribute path;
	 * pre-substituted server-side when the PHP path is engaged and the
	 * resolved key is non-empty — see below), `attribution`, `maxZoom`.
	 *
	 * **PHP-supplied key path.** When a provider record carries the
	 * optional `apiKey` field (engaged via the
	 * `kntnt_gpx_blocks_tile_providers` filter), the per-block
	 * `attributes.tileApiKeys[ providerId ]` value is ignored entirely
	 * and the editor must not render an API-key TextControl for that
	 * provider. This shaper:
	 *
	 * - emits `apiKeyManagedExternally: true` per provider so the editor
	 *   knows to hide the TextControl;
	 * - pre-substitutes `{KEY}` in every style URL when the resolved key
	 *   is non-empty, so the preview can mount the URL directly without
	 *   invoking the client-side `substituteTileApiKey()` helper;
	 * - leaves `{KEY}` intact and logs a `Plugin::warning()` naming only
	 *   the provider id (never the key value) when the resolved key is
	 *   empty or whitespace-only — the editor preview then detects the
	 *   unsubstituted `{KEY}` and ships polyline-only, mirroring the
	 *   frontend's fail-closed contract.
	 *
	 * The `apiKey` itself is **never** part of the editor payload — only
	 * the boolean flag and the resolved URL ever reach the browser. The
	 * shape is deliberately explicit so a future change to the registry's
	 * internal record type does not silently leak through the editor
	 * data; only the fields listed below ever reach the browser.
	 *
	 * @since 1.0.0
	 *
	 * @param array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     default: string,
	 *     styles: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 *     apiKey?: string,
	 * }> $providers Validated provider records keyed by id.
	 *
	 * @return array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     default: string,
	 *     apiKeyManagedExternally: bool,
	 *     styles: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 * }>
	 */
	private static function shape_providers( array $providers ): array {

		$out = [];

		foreach ( $providers as $id => $record ) {

			// Detect PHP-supplied key engagement. Presence of `apiKey` on
			// the validated record (not its value) is the engagement
			// signal. An empty PHP key fails closed — the URL is left
			// with its `{KEY}` placeholder and a warning is logged so
			// the misconfiguration surfaces in the log.
			$php_path_engaged = array_key_exists( 'apiKey', $record );
			$php_key          = $php_path_engaged ? $record['apiKey'] : '';
			$php_key_empty    = $php_path_engaged && '' === $php_key;
			if ( $php_key_empty ) {
				Plugin::warning(
					sprintf(
						'Editor_Data_Enqueuer: PHP-supplied apiKey for tile provider "%s" is empty; editor preview will fail closed (polyline-only).',
						$id
					)
				);
			}

			// Compose the per-style sub-map. The shape mirrors the
			// validator's typed style record verbatim; the validator has
			// already enforced the URL/maxZoom/{KEY}-placeholder rules.
			// When the PHP path is engaged with a non-empty key, the
			// `{KEY}` placeholder is substituted server-side so the
			// editor preview never sees the raw key in its props graph;
			// when the PHP key is empty, `{KEY}` is left intact so the
			// preview's fail-closed detector (unsubstituted `{KEY}`) ships
			// polyline-only.
			$styles = [];
			foreach ( $record['styles'] as $style_id => $style ) {
				$url = $style['url'];
				if ( $php_path_engaged && ! $php_key_empty ) {
					$url = str_replace( '{KEY}', $php_key, $url );
				}
				$styles[ $style_id ] = [
					'label'       => $style['label'],
					'url'         => $url,
					'attribution' => $style['attribution'],
					'maxZoom'     => $style['maxZoom'],
				];
			}

			$entry = [
				'label'                   => $record['label'],
				'requiresKey'             => $record['requiresKey'],
				'default'                 => $record['default'],
				'apiKeyManagedExternally' => $php_path_engaged,
				'styles'                  => $styles,
			];
			if ( isset( $record['signupUrl'] ) ) {
				$entry['signupUrl'] = $record['signupUrl'];
			}
			if ( isset( $record['subdomains'] ) ) {
				$entry['subdomains'] = $record['subdomains'];
			}
			$out[ $id ] = $entry;

		}

		return $out;

	}

	/**
	 * Shapes the overlay-provider registry for the editor payload.
	 *
	 * Forwards the nested overlay-provider/layer hierarchy verbatim into
	 * the inline payload so the editor's `OverlaysPanel` can render one
	 * sub-section per provider — provider label as a header, conditional
	 * API-key TextControl + signup ExternalLink for `requiresKey === true`
	 * providers, and one ToggleControl per layer — and so
	 * `MapEditorPreview` can mount each enabled layer's tile layer via
	 * `L.tileLayer()`. Provider-level fields surfaced: `label`,
	 * `requiresKey`, optional `signupUrl`, optional `subdomains`, and
	 * `apiKeyManagedExternally` (the boolean flag the editor reads to
	 * decide whether to render the per-provider API-key TextControl).
	 * Per-layer fields surfaced under `layers[ id ]`: `label`, `url`
	 * (with `{KEY}` left intact for the attribute path; pre-substituted
	 * server-side when the PHP path is engaged and the resolved key is
	 * non-empty — see below), `attribution`, `maxZoom`.
	 *
	 * **PHP-supplied key path.** When an overlay-provider record carries
	 * the optional `apiKey` field (engaged via the
	 * `kntnt_gpx_blocks_tile_overlays` filter), the per-block
	 * `attributes.tileOverlayApiKeys[ providerId ]` value is ignored
	 * entirely and the editor must not render an API-key TextControl
	 * for that provider. This shaper:
	 *
	 * - emits `apiKeyManagedExternally: true` per overlay provider so
	 *   the editor knows to hide the TextControl;
	 * - pre-substitutes `{KEY}` in every layer URL when the resolved key
	 *   is non-empty, so the preview can mount the URL directly without
	 *   invoking the client-side `substituteTileApiKey()` helper;
	 * - leaves `{KEY}` intact and logs a `Plugin::warning()` naming only
	 *   the overlay-provider id (never the key value) when the resolved
	 *   key is empty or whitespace-only — the editor preview's
	 *   `resolveOverlaysForPreview()` then detects the unsubstituted
	 *   `{KEY}` and drops just that layer, mirroring the frontend's
	 *   asymmetric fail-closed contract for overlays (no polyline-only
	 *   equivalent; the base map and other overlays still render).
	 *
	 * The `apiKey` itself is **never** part of the editor payload — only
	 * the boolean flag and the resolved URL ever reach the browser. The
	 * shape is deliberately explicit so a future change to the registry's
	 * internal record type does not silently leak through the editor
	 * data; only the fields listed below ever reach the browser.
	 *
	 * @since 1.0.0
	 *
	 * @param array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     layers: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 *     apiKey?: string,
	 * }> $overlays Validated overlay-provider records keyed by id.
	 *
	 * @return array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     apiKeyManagedExternally: bool,
	 *     layers: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 * }>
	 */
	private static function shape_overlays( array $overlays ): array {

		$out = [];

		foreach ( $overlays as $id => $record ) {

			// Detect PHP-supplied key engagement. Presence of `apiKey` on
			// the validated record (not its value) is the engagement
			// signal. An empty PHP key fails closed at resolve time (the
			// affected layer is dropped from the overlay stack) — the
			// editor preview detects this by spotting `{KEY}` still
			// present in the URL and skips mounting that layer; the
			// warning here surfaces the misconfiguration in the log.
			$php_path_engaged = array_key_exists( 'apiKey', $record );
			$php_key          = $php_path_engaged ? $record['apiKey'] : '';
			$php_key_empty    = $php_path_engaged && '' === $php_key;
			if ( $php_key_empty ) {
				Plugin::warning(
					sprintf(
						'Editor_Data_Enqueuer: PHP-supplied apiKey for tile-overlay provider "%s" is empty; editor preview will drop its layers (base map and other overlays still render).',
						$id
					)
				);
			}

			// Compose the per-layer sub-map. The shape mirrors the
			// validator's typed layer record verbatim; the validator has
			// already enforced the URL/maxZoom/{KEY}-placeholder rules.
			// When the PHP path is engaged with a non-empty key, the
			// `{KEY}` placeholder is substituted server-side so the
			// editor preview never sees the raw key in its props graph;
			// when the PHP key is empty, `{KEY}` is left intact so the
			// preview's fail-closed detector (unsubstituted `{KEY}`)
			// drops just the affected layer.
			$layers = [];
			foreach ( $record['layers'] as $layer_id => $layer ) {
				$url = $layer['url'];
				if ( $php_path_engaged && ! $php_key_empty ) {
					$url = str_replace( '{KEY}', $php_key, $url );
				}
				$layers[ $layer_id ] = [
					'label'       => $layer['label'],
					'url'         => $url,
					'attribution' => $layer['attribution'],
					'maxZoom'     => $layer['maxZoom'],
				];
			}

			$entry = [
				'label'                   => $record['label'],
				'requiresKey'             => $record['requiresKey'],
				'apiKeyManagedExternally' => $php_path_engaged,
				'layers'                  => $layers,
			];
			if ( isset( $record['signupUrl'] ) ) {
				$entry['signupUrl'] = $record['signupUrl'];
			}
			if ( isset( $record['subdomains'] ) ) {
				$entry['subdomains'] = $record['subdomains'];
			}
			$out[ $id ] = $entry;

		}

		return $out;

	}

}
