<?php
/**
 * Inlines the editor-only `window.kntntGpxBlocks` registry payload.
 *
 * Exposes the validated tile-provider and overlay registries to the block
 * editor so the GPX Map block's Inspector controls can enumerate them. Both
 * the per-block tile-provider dropdown (issue #79) and the overlay toggles
 * (issue #80) read from the same global; this enqueuer is the single source
 * the editor JS consults.
 *
 * The payload is JSON-encoded and attached as a `'before'` inline script on
 * the GPX Map block's editor handle, so it lands in the editor document
 * before the block's React entry runs and reads the global. API keys are
 * deliberately excluded — those are per-block (`attributes.tileApiKeys`,
 * a provider-keyed object) and never leave PHP except as the substituted
 * `{KEY}` value in the rendered tile URL.
 *
 * @package Kntnt\Gpx_Blocks
 * @since   1.0.0
 */

declare( strict_types = 1 );

namespace Kntnt\Gpx_Blocks\Bootstrap;

use Kntnt\Gpx_Blocks\Plugin;
use Kntnt\Gpx_Blocks\Rendering\Tile_Layer_Registry;

/**
 * Enqueues the editor-only `window.kntntGpxBlocks` registry payload.
 *
 * Constructed once by Plugin and bound to `enqueue_block_editor_assets` so
 * the global is set up on every editor request — post, site, widgets, and
 * navigation — before the GPX Map block's editor script reads from it.
 *
 * @package Kntnt\Gpx_Blocks
 * @since 1.0.0
 */
final class Editor_Data_Enqueuer {

	/**
	 * Editor script handle generated by `register_block_type()` for the GPX
	 * Map block.
	 *
	 * Follows WordPress's `generate_block_asset_handle()` convention:
	 * `<namespace>-<slug>-editor-script`. The block.json `name` is
	 * `kntnt-gpx-blocks/map`, so the handle is
	 * `kntnt-gpx-blocks-map-editor-script`.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	private const MAP_EDITOR_HANDLE = 'kntnt-gpx-blocks-map-editor-script';

	/**
	 * Constructs the enqueuer with an injectable registry.
	 *
	 * Tests inject a synthetic registry; production wiring uses a fresh
	 * `Tile_Layer_Registry` per request (its filter-evaluation cache is
	 * per-instance and that is fine for a single editor render).
	 *
	 * @since 1.0.0
	 *
	 * @param Tile_Layer_Registry|null $registry Tile-layer registry, or null
	 *                                           to construct a default one
	 *                                           lazily inside `enqueue()`.
	 */
	public function __construct( private readonly ?Tile_Layer_Registry $registry = null ) {}

	/**
	 * Builds the editor data payload and inlines it as a `before` script.
	 *
	 * Wired to `enqueue_block_editor_assets`. Reads the validated provider
	 * and overlay registries and forwards the fields the editor's Inspector
	 * controls and `MapEditorPreview` need: `label` and `requiresKey` drive
	 * the dropdown and the conditional API-key text field, the optional
	 * `signupUrl` powers the "Get one" help-text link, and the URL /
	 * attribution / maxZoom / optional subdomains let the preview mount the
	 * selected provider's tile layer directly via `L.tileLayer()`. API keys
	 * are deliberately *not* in the payload — they remain a per-block
	 * attribute (`tileApiKeys[ tileProvider ]`) and reach the browser only
	 * as the substituted `{KEY}` value at render time. When JSON encoding
	 * fails or the
	 * inline-script call is unavailable, a warning is logged and the method
	 * returns silently — the editor reads `window.kntntGpxBlocks` defensively
	 * and degrades to an empty Tiles dropdown rather than throwing.
	 *
	 * @since 1.0.0
	 */
	public function enqueue(): void {

		// Resolve the registry from the constructor or build a default.
		$registry = $this->registry ?? new Tile_Layer_Registry();

		// Compose the payload from the validated registries. Both lists are
		// keyed by id; the editor reads `id` and `label` per entry.
		$payload = [
			'providers' => self::shape_providers( $registry->get_providers() ),
			'overlays'  => self::shape_overlays( $registry->get_overlays() ),
		];

		// Encode the payload. wp_json_encode() returns false on failure, in
		// which case we log a warning and bail rather than emit an invalid
		// global.
		$json = wp_json_encode( $payload );
		if ( ! is_string( $json ) ) {
			Plugin::warning( 'Editor_Data_Enqueuer: wp_json_encode failed; window.kntntGpxBlocks not emitted.' );
			return;
		}

		// Attach the inline script to the GPX Map block's editor handle so
		// the global is set up before the React entry reads it. Position
		// `before` ensures the assignment runs before the entry's IIFE.
		$inline = sprintf( 'window.kntntGpxBlocks = %s;', $json );
		wp_add_inline_script( self::MAP_EDITOR_HANDLE, $inline, 'before' );

	}

	/**
	 * Shapes the provider registry for the editor payload.
	 *
	 * Forwards the nested provider/style hierarchy verbatim into the
	 * inline payload so the editor's `TilesPanel` can drive its two
	 * `SelectControl`s plus the conditional API-key field, and so
	 * `MapEditorPreview` can mount the resolved style's tile layer via
	 * `L.tileLayer()`. Provider-level fields surfaced: `label`,
	 * `requiresKey`, `default`, optional `signupUrl`, optional
	 * `subdomains`. Per-style fields surfaced under `styles[ id ]`:
	 * `label`, `url` (with `{KEY}` left intact for paid providers),
	 * `attribution`, `maxZoom`. The shape is deliberately explicit so a
	 * future change to the registry's internal record type does not
	 * silently leak through the editor data; only the fields listed below
	 * ever reach the browser. The per-block API keys are *never* part of
	 * this payload — they live in `attributes.tileApiKeys` (a
	 * provider-keyed object) and the entry for the currently-selected
	 * provider is substituted into `{KEY}` client-side by `edit.tsx`
	 * before forwarding the URL to the preview.
	 *
	 * @since 1.0.0
	 *
	 * @param array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     default: string,
	 *     styles: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 * }> $providers Validated provider records keyed by id.
	 *
	 * @return array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     default: string,
	 *     styles: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 * }>
	 */
	private static function shape_providers( array $providers ): array {

		$out = [];

		foreach ( $providers as $id => $record ) {

			// Compose the per-style sub-map. The shape mirrors the
			// validator's typed style record verbatim; the validator has
			// already enforced the URL/maxZoom/{KEY}-placeholder rules.
			$styles = [];
			foreach ( $record['styles'] as $style_id => $style ) {
				$styles[ $style_id ] = [
					'label'       => $style['label'],
					'url'         => $style['url'],
					'attribution' => $style['attribution'],
					'maxZoom'     => $style['maxZoom'],
				];
			}

			$entry = [
				'label'       => $record['label'],
				'requiresKey' => $record['requiresKey'],
				'default'     => $record['default'],
				'styles'      => $styles,
			];
			if ( isset( $record['signupUrl'] ) ) {
				$entry['signupUrl'] = $record['signupUrl'];
			}
			if ( isset( $record['subdomains'] ) ) {
				$entry['subdomains'] = $record['subdomains'];
			}
			$out[ $id ] = $entry;

		}

		return $out;

	}

	/**
	 * Shapes the overlay-provider registry for the editor payload.
	 *
	 * Forwards the nested overlay-provider/layer hierarchy verbatim into
	 * the inline payload so the editor's `OverlaysPanel` can render one
	 * sub-section per provider — provider label as a header, conditional
	 * API-key TextControl + signup ExternalLink for `requiresKey === true`
	 * providers, and one ToggleControl per layer — and so
	 * `MapEditorPreview` can mount each enabled layer's tile layer via
	 * `L.tileLayer()`. Provider-level fields surfaced: `label`,
	 * `requiresKey`, optional `signupUrl`, optional `subdomains`. Per-layer
	 * fields surfaced under `layers[ id ]`: `label`, `url` (with `{KEY}`
	 * left intact for paid providers), `attribution`, `maxZoom`. The shape
	 * is deliberately explicit so a future change to the registry's
	 * internal record type does not silently leak through the editor
	 * data; only the fields listed below ever reach the browser. The
	 * per-block API keys are *never* part of this payload — they live in
	 * `attributes.tileOverlayApiKeys` (a provider-keyed object) and the
	 * entry for each enabled overlay layer's provider is substituted into
	 * `{KEY}` client-side by `edit.tsx` before forwarding each layer's
	 * URL to the preview.
	 *
	 * @since 1.0.0
	 *
	 * @param array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     layers: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 * }> $overlays Validated overlay-provider records keyed by id.
	 *
	 * @return array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     layers: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 * }>
	 */
	private static function shape_overlays( array $overlays ): array {

		$out = [];

		foreach ( $overlays as $id => $record ) {

			// Compose the per-layer sub-map. The shape mirrors the
			// validator's typed layer record verbatim; the validator has
			// already enforced the URL/maxZoom/{KEY}-placeholder rules.
			$layers = [];
			foreach ( $record['layers'] as $layer_id => $layer ) {
				$layers[ $layer_id ] = [
					'label'       => $layer['label'],
					'url'         => $layer['url'],
					'attribution' => $layer['attribution'],
					'maxZoom'     => $layer['maxZoom'],
				];
			}

			$entry = [
				'label'       => $record['label'],
				'requiresKey' => $record['requiresKey'],
				'layers'      => $layers,
			];
			if ( isset( $record['signupUrl'] ) ) {
				$entry['signupUrl'] = $record['signupUrl'];
			}
			if ( isset( $record['subdomains'] ) ) {
				$entry['subdomains'] = $record['subdomains'];
			}
			$out[ $id ] = $entry;

		}

		return $out;

	}

}
