<?php
/**
 * Inlines the editor-only `window.kntntGpxBlocks` registry payload.
 *
 * Exposes the validated tile-provider and overlay registries to the block
 * editor so the GPX Map block's Inspector controls can enumerate them. Both
 * the per-block tile-provider dropdown (issue #79) and the overlay toggles
 * (issue #80) read from the same global; this enqueuer is the single source
 * the editor JS consults.
 *
 * The payload is JSON-encoded and attached as a `'before'` inline script on
 * the GPX Map block's editor handle, so it lands in the editor document
 * before the block's React entry runs and reads the global. API keys are
 * deliberately excluded from the payload as raw values: base-provider
 * keys are read from the site-wide `kntnt_gpx_blocks_tile_provider_keys`
 * option (issue #149) and substituted into `{KEY}` server-side before
 * the URL reaches the editor; overlay-provider keys are read from the
 * parallel `kntnt_gpx_blocks_tile_overlay_keys` option (issue #150) and
 * substituted into `{KEY}` server-side too; PHP-supplied keys (engaged
 * via the optional `apiKey` field on a `kntnt_gpx_blocks_tile_providers`
 * or `kntnt_gpx_blocks_tile_overlays` callback) are substituted
 * server-side before the URL reaches the editor — the editor receives a
 * boolean `apiKeyManagedExternally` flag per provider but never the key
 * itself.
 *
 * @package Kntnt\Gpx_Blocks
 * @since   1.0.0
 */

declare( strict_types = 1 );

namespace Kntnt\Gpx_Blocks\Bootstrap;

use Kntnt\Gpx_Blocks\Admin\Settings_Page;
use Kntnt\Gpx_Blocks\Plugin;
use Kntnt\Gpx_Blocks\Rendering\Tile_Layer_Registry;

/**
 * Enqueues the editor-only `window.kntntGpxBlocks` registry payload.
 *
 * Constructed once by Plugin and bound to `enqueue_block_editor_assets` so
 * the global is set up on every editor request — post, site, widgets, and
 * navigation — before the GPX Map block's editor script reads from it.
 *
 * @package Kntnt\Gpx_Blocks
 * @since 1.0.0
 */
final class Editor_Data_Enqueuer {

	/**
	 * Editor script handle generated by `register_block_type()` for the GPX
	 * Map block.
	 *
	 * Follows WordPress's `generate_block_asset_handle()` convention:
	 * `<namespace>-<slug>-editor-script`. The block.json `name` is
	 * `kntnt-gpx-blocks/map`, so the handle is
	 * `kntnt-gpx-blocks-map-editor-script`.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	private const MAP_EDITOR_HANDLE = 'kntnt-gpx-blocks-map-editor-script';

	/**
	 * Constructs the enqueuer with an injectable registry.
	 *
	 * Tests inject a synthetic registry; production wiring uses a fresh
	 * `Tile_Layer_Registry` per request (its filter-evaluation cache is
	 * per-instance and that is fine for a single editor render).
	 *
	 * @since 1.0.0
	 *
	 * @param Tile_Layer_Registry|null $registry Tile-layer registry, or null
	 *                                           to construct a default one
	 *                                           lazily inside `enqueue()`.
	 */
	public function __construct( private readonly ?Tile_Layer_Registry $registry = null ) {}

	/**
	 * Builds the editor data payload and inlines it as a `before` script.
	 *
	 * Wired to `enqueue_block_editor_assets`. Reads the validated provider
	 * and overlay registries and forwards the fields the editor's Inspector
	 * controls and `MapEditorPreview` need: `label` and `requiresKey` drive
	 * the dropdown and the conditional API-key text field, the optional
	 * `signupUrl` powers the "Get one" help-text link, and the URL /
	 * attribution / maxZoom / optional subdomains let the preview mount the
	 * selected provider's tile layer directly via `L.tileLayer()`. API keys
	 * are deliberately *not* in the payload — base-provider keys live in
	 * the site-wide option (issue #149) and reach the browser only as the
	 * substituted `{KEY}` value at render time. When JSON encoding fails
	 * or the inline-script call is unavailable, a warning is logged and
	 * the method returns silently — the editor reads `window.kntntGpxBlocks`
	 * defensively and degrades to an empty Tiles dropdown rather than
	 * throwing.
	 *
	 * @since 1.0.0
	 */
	public function enqueue(): void {

		// Resolve the registry from the constructor or build a default.
		$registry = $this->registry ?? new Tile_Layer_Registry();

		// Compose the payload from the validated registries. Both lists are
		// keyed by id; the editor reads `id` and `label` per entry. The two
		// halves share a single shaper parametrised over the nested-collection
		// key (`styles` vs `layers`), the `default` field (providers only),
		// and the warning wording that distinguishes the two halves in the
		// log so a site builder can locate the failure from the log alone.
		// The `settingsUrl` and `canManageSettings` fields surface the
		// site-wide tile-API-key admin page (issue #149) to the Map
		// block's Inspector so its key-required Notice can link to the
		// page when the current user holds `manage_options`. The URL is
		// emitted unconditionally; the editor JS chooses whether to
		// render it as a link or as plain text based on the capability
		// flag.
		$payload = [
			'providers'         => self::shape_collection(
				$registry->get_providers(),
				'styles',
				true,
				'tile provider',
				'fail closed (polyline-only)',
				Settings_Page::get_stored_keys(),
			),
			'overlays'          => self::shape_collection(
				$registry->get_overlays(),
				'layers',
				false,
				'tile-overlay provider',
				'drop its layers (base map and other overlays still render)',
				Settings_Page::get_stored_overlay_keys(),
			),
			'settingsUrl'       => self::resolve_settings_url(),
			'canManageSettings' => function_exists( 'current_user_can' ) && current_user_can( 'manage_options' ),
		];

		// Encode the payload. wp_json_encode() returns false on failure, in
		// which case we log a warning and bail rather than emit an invalid
		// global.
		$json = wp_json_encode( $payload );
		if ( ! is_string( $json ) ) {
			Plugin::warning( 'Editor_Data_Enqueuer: wp_json_encode failed; window.kntntGpxBlocks not emitted.' );
			return;
		}

		// Attach the inline script to the GPX Map block's editor handle so
		// the global is set up before the React entry reads it. Position
		// `before` ensures the assignment runs before the entry's IIFE.
		$inline = sprintf( 'window.kntntGpxBlocks = %s;', $json );
		wp_add_inline_script( self::MAP_EDITOR_HANDLE, $inline, 'before' );

	}

	/**
	 * Shapes a registry collection (providers or overlays) for the editor
	 * payload.
	 *
	 * Both halves of the editor payload share the same record structure:
	 * a provider-level envelope (`label`, `requiresKey`, optional
	 * `signupUrl`, optional `subdomains`, optional `apiKey`) wrapping a
	 * nested map of child records keyed by id, each carrying `label`,
	 * `url`, `attribution`, `maxZoom`. The two halves differ only in
	 * three mechanical points:
	 *
	 * - the nested-collection key — `styles` for base providers,
	 *   `layers` for overlay providers;
	 * - the presence of a `default` field — base providers carry it (the
	 *   default style id), overlay providers do not;
	 * - the warning wording in the fail-closed log line — "tile provider"
	 *   + "fail closed (polyline-only)" for base providers; "tile-overlay
	 *   provider" + "drop its layers (base map and other overlays still
	 *   render)" for overlays. The wording distinguishes the two halves
	 *   so a site builder can locate the failure from the log alone.
	 *
	 * Everything else — validation expectations, key pruning, record
	 * reconstruction, `apiKey` handling, `subdomains` inheritance, the
	 * fail-closed `{KEY}`-survives invariant — is identical. The shaper
	 * surfaces `apiKeyManagedExternally` (the boolean flag the editor
	 * reads to decide whether to render the per-provider API-key
	 * TextControl) and pre-substitutes `{KEY}` in every child URL when
	 * the PHP path is engaged with a non-empty key; when the PHP key is
	 * empty, `{KEY}` is left intact so the editor preview's fail-closed
	 * detector (unsubstituted `{KEY}`) ships polyline-only (base
	 * providers) or drops just the affected layer (overlays).
	 *
	 * The `apiKey` itself is **never** part of the editor payload — only
	 * the boolean flag and the resolved URL ever reach the browser. The
	 * shape is deliberately explicit so a future change to the registry's
	 * internal record type does not silently leak through the editor
	 * data; only the fields listed below ever reach the browser.
	 *
	 * @since 1.0.0
	 *
	 * @param array<string, array{
	 *     label: string,
	 *     requiresKey: bool,
	 *     default?: string,
	 *     styles?: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     layers?: array<string, array{
	 *         label: string,
	 *         url: string,
	 *         attribution: string,
	 *         maxZoom: int,
	 *     }>,
	 *     signupUrl?: string,
	 *     subdomains?: list<string>,
	 *     apiKey?: string,
	 * }>                                          $records             Validated provider/overlay records keyed by id.
	 * @param 'styles'|'layers'                    $nested_key          Key under which the child collection lives on each
	 *                                                                  record (`styles` for base providers, `layers` for
	 *                                                                  overlay providers).
	 * @param bool                                 $has_default         Whether records carry a `default` field that must
	 *                                                                  be forwarded into the editor payload (true for base
	 *                                                                  providers, false for overlay providers).
	 * @param string                               $kind_for_warning    Human-readable record-kind label spliced into the
	 *                                                                  fail-closed warning (`'tile provider'` or
	 *                                                                  `'tile-overlay provider'`).
	 * @param string                               $consequence_phrase  Trailing phrase spliced into the fail-closed warning
	 *                                                                  describing the editor-preview consequence
	 *                                                                  (`'fail closed (polyline-only)'` or
	 *                                                                  `'drop its layers (base map and other overlays still render)'`).
	 *
	 * @param array<string, string>                $option_keys         Per-provider option-layer keys keyed by provider id.
	 *                                                                  An entry pre-substitutes `{KEY}` server-side from the
	 *                                                                  site-wide option (issue #149 for base providers, #150
	 *                                                                  for overlay providers) for providers where the PHP
	 *                                                                  path is *not* engaged. Pass the empty array to render
	 *                                                                  no option-layer substitution at all.
	 *
	 * @return array<string, array<string, mixed>>
	 */
	private static function shape_collection(
		array $records,
		string $nested_key,
		bool $has_default,
		string $kind_for_warning,
		string $consequence_phrase,
		array $option_keys = [],
	): array {

		$out = [];

		foreach ( $records as $id => $record ) {

			// Detect PHP-supplied key engagement. Presence of `apiKey` on
			// the validated record (not its value) is the engagement
			// signal. An empty PHP key fails closed — the URL is left
			// with its `{KEY}` placeholder and a warning is logged so
			// the misconfiguration surfaces in the log. The base-provider
			// preview ships polyline-only; the overlay preview drops just
			// the affected layer (base map and other overlays still
			// render) — the consequence phrase distinguishes the two so a
			// site builder can locate the failure from the log alone.
			$php_path_engaged = array_key_exists( 'apiKey', $record );
			$php_key          = $php_path_engaged ? $record['apiKey'] : '';
			$php_key_empty    = $php_path_engaged && '' === $php_key;
			if ( $php_key_empty ) {
				Plugin::warning(
					sprintf(
						'Editor_Data_Enqueuer: PHP-supplied apiKey for %s "%s" is empty; editor preview will %s.',
						$kind_for_warning,
						$id,
						$consequence_phrase,
					)
				);
			}

			// Resolve the option-layer substitution candidate. Issue #149
			// centralised per-base-provider tile API keys in a site-wide
			// option; for collections that opt into the option-layer
			// flow (`$option_keys` non-empty), a present entry pre-
			// substitutes `{KEY}` server-side so the editor preview
			// mounts the tile layer the same way the frontend does.
			// PHP engagement still wins — `$option_keys` is only
			// consulted when the PHP path is *not* engaged for this id.
			$raw_option_key       = $option_keys[ $id ] ?? '';
			$option_key           = is_string( $raw_option_key ) ? trim( $raw_option_key ) : '';
			$option_path_engaged  = ! $php_path_engaged && $option_key !== '';

			// Compose the nested child sub-map. The shape mirrors the
			// validator's typed child record verbatim; the validator has
			// already enforced the URL/maxZoom/{KEY}-placeholder rules.
			// When either the PHP path is engaged with a non-empty key,
			// or the option-layer key is non-empty, the `{KEY}`
			// placeholder is substituted server-side so the editor
			// preview never sees the raw key in its props graph; when
			// neither layer supplies a usable key, `{KEY}` is left
			// intact so the preview's fail-closed detector
			// (unsubstituted `{KEY}`) ships polyline-only (base
			// providers) or drops just the affected layer (overlays).
			$nested = $record[ $nested_key ] ?? [];
			$children = [];
			foreach ( $nested as $child_id => $child ) {
				$url = $child['url'];
				if ( $php_path_engaged && ! $php_key_empty ) {
					$url = str_replace( '{KEY}', $php_key, $url );
				} elseif ( $option_path_engaged ) {
					$url = str_replace( '{KEY}', $option_key, $url );
				}
				$children[ $child_id ] = [
					'label'       => $child['label'],
					'url'         => $url,
					'attribution' => $child['attribution'],
					'maxZoom'     => $child['maxZoom'],
				];
			}

			// Compose the per-record entry. The optional `default` field
			// is forwarded only for record kinds that carry it (base
			// providers), sitting between `requiresKey` and
			// `apiKeyManagedExternally` to mirror its position on the
			// validated input record; optional `signupUrl` and `subdomains`
			// are forwarded whenever present.
			$entry = [
				'label'       => $record['label'],
				'requiresKey' => $record['requiresKey'],
			];
			if ( $has_default && isset( $record['default'] ) ) {
				$entry['default'] = $record['default'];
			}
			$entry['apiKeyManagedExternally'] = $php_path_engaged;
			$entry[ $nested_key ] = $children;
			if ( isset( $record['signupUrl'] ) ) {
				$entry['signupUrl'] = $record['signupUrl'];
			}
			if ( isset( $record['subdomains'] ) ) {
				$entry['subdomains'] = $record['subdomains'];
			}
			$out[ $id ] = $entry;

		}

		return $out;

	}

	/**
	 * Resolves the absolute URL of the plugin's settings page.
	 *
	 * Prefers `menu_page_url()`, the WordPress canonical way to obtain a
	 * registered admin page URL. The function returns the URL when the
	 * page is registered at the time of the call (which is true for
	 * every editor request, because `admin_menu` fires before
	 * `enqueue_block_editor_assets`); a defensive fall-back builds the
	 * URL from `admin_url()` for the unusual case where the function is
	 * missing or returns an empty string. When neither is available
	 * (e.g. a non-WordPress test runner), the method returns the empty
	 * string and the editor JS treats the absent URL as a non-link.
	 *
	 * @since 1.0.0
	 *
	 * @return string Absolute URL of `Settings → Kntnt GPX Blocks`, or
	 *                `''` when no resolution path succeeds.
	 */
	private static function resolve_settings_url(): string {

		if ( function_exists( 'menu_page_url' ) ) {
			$url = menu_page_url( Settings_Page::MENU_SLUG, false );
			if ( is_string( $url ) && $url !== '' ) {
				return $url;
			}
		}

		if ( function_exists( 'admin_url' ) ) {
			return admin_url( 'options-general.php?page=' . Settings_Page::MENU_SLUG );
		}

		return '';

	}

}
